version: '3.7'
services:
  app:
    command: bash -c "rm -f /rails/tmp/pids/server.pid && bundle exec puma -C config/puma_production.rb"
  nginx:
    volumes:
      - ./nginx/conf.d/production/:/etc/nginx/conf.d
